### ISSUE TITLE
增加composer支持

### ISSUE THREAD

**Issue by tourze** [shixinke/phpstorm-for-php-framework#1]
首先谢谢作者带来这样的好项目。

希望作者能继续完善项目，增加composer的支持。

**Comment by jinchunguang** [comment]
readme文件有图有真相,赞!

**Comment by shixinke** [comment]
这是一个自动补全的类， @tourze ，你是希望通过composer安装吧？增加composer必须遵循psr规范，毕竟这是一个工具，不是一个类库，以后可能增加支持，谢谢关注
