### ISSUE TITLE
redis setex方法有错误 第二个参数传ttl

### ISSUE THREAD

**Issue by aarontang** [shixinke/phpstorm-for-php-framework#12]
> /**
     * 
     *设置键值并设置有效期
     * @example $redis->setex('key', 3600, 'value');
     * @param string $key 设置的缓存键
     * @param string $value 设置的缓存值
     * @param int $ttl 有效期
     * @return bool
     */
    public function setex(string $key, string $value, int $ttl): bool
    {
    
    }

**Comment by shixinke** [comment]
感谢指出bug，已修正
