### ISSUE TITLE
望补充下这些 msgpack.so amqp.so igbinary.so redis.so donkeyid.so seaslog.so

### ISSUE THREAD

**Issue by km3945** [shixinke/phpstorm-for-php-framework#3]
msgpack.so
amqp.so
igbinary.so
redis.so
donkeyid.so
seaslog.so

**Comment by shixinke** [comment]
redis已经有了,msgpack,seaslog已经加了，igbinary和donkeyid相对于前几个，没那么广泛，amqp依赖于rabbitmq，安装略麻烦，这里推荐我的另外一个工具:https://github.com/shixinke/php-document-creator   ,
这个可以生成任何PHP扩展的文档，它可以通过composer安装
