### ISSUE TITLE
yaf很多方法识别成 return void了

### ISSUE THREAD

**Issue by tofuliang** [shixinke/phpstorm-for-php-framework#5]
如图,在PHPstorm中会报一个警告.
![yaf_return](https://user-images.githubusercontent.com/1814685/38714606-9ebfb564-3f09-11e8-977c-301df599b0ec.png)
![void](https://user-images.githubusercontent.com/1814685/38714605-9e75f8a2-3f09-11e8-80b8-0f6fe9a4b54a.png)

**Comment by shixinke** [comment]
最近比较忙，我会尽快抽时间将这个更新

**Comment by shixinke** [comment]
相关问题已经修复，请下载最新版验证
